spring:
  application:
    name: user-management-api
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        search:
          backend:
            type: lucene
            directory:
              type: local-heap

server:
  port: 8084

logging:
  level:
    com.example.usermanagement: DEBUG
    org.springframework.web: INFO
    org.hibernate.search: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log

api:
  external:
    dummyjson:
      base-url: https://dummyjson.com
      retry:
        max-attempts: 3
        delay: 1000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html